// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO_ZWHocuRJ-ji1e5VHe2CBmH-CbxNc4g',
    appId: '1:943250059824:web:1267a1a61ade00416a73f5',
    messagingSenderId: '943250059824',
    projectId: 'spotifyclone010',
    authDomain: 'spotifyclone010.firebaseapp.com',
    storageBucket: 'spotifyclone010.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnhSqvvGNowB_Ye0cY-ECWOMpHD_c3tSU',
    appId: '1:943250059824:android:db627c0e41f96ff06a73f5',
    messagingSenderId: '943250059824',
    projectId: 'spotifyclone010',
    storageBucket: 'spotifyclone010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiCvaXRXYBfqiyxWFCZRCXNCmnEGGspQc',
    appId: '1:943250059824:ios:f7e746fd0c8429d66a73f5',
    messagingSenderId: '943250059824',
    projectId: 'spotifyclone010',
    storageBucket: 'spotifyclone010.firebasestorage.app',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiCvaXRXYBfqiyxWFCZRCXNCmnEGGspQc',
    appId: '1:943250059824:ios:f7e746fd0c8429d66a73f5',
    messagingSenderId: '943250059824',
    projectId: 'spotifyclone010',
    storageBucket: 'spotifyclone010.firebasestorage.app',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO_ZWHocuRJ-ji1e5VHe2CBmH-CbxNc4g',
    appId: '1:943250059824:web:1f61ee204a4a88936a73f5',
    messagingSenderId: '943250059824',
    projectId: 'spotifyclone010',
    authDomain: 'spotifyclone010.firebaseapp.com',
    storageBucket: 'spotifyclone010.firebasestorage.app',
  );
}
